<?php

namespace Tools4Schools\Tests\SDK\Resources;

use Http\Mock\Client;
use PHPUnit\Framework\TestCase;
use Tools4Schools\SDK\Resources\ResourceModel;
use Tools4Schools\SDK\Tools4Schools;

class ResourceModelTest extends TestCase
{
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $options['client'] = new Client();
        $t4s =  new Tools4Schools($options);
    }

    public function attributeManipulation()
    {
        $model = new ResourceModelStub;
    }

    /** @test */
    public function create_method_saves_new_model()
    {
        $_SERVER['_resource_model.saved'] = false;
        $model = ResourceModelSaveStub::create(['name'=>'Timothy']);

        $this->assertEquals('Timothy',$model->name);
    }
}

class ResourceModelStub extends ResourceModel
{

}

class ResourceModelSaveStub extends ResourceModel
{
    // mock the httpclient should return an instance of clientbuilder
   /* public function getClient()
    {

        //return $mock;
    }*/
}